### ISSUE TITLE
Posible excepción ClassCastException de Usuario

### ISSUE THREAD

**Issue by manelcc** [adrianfanjul/FlujoLogin#2]
@adrianfanjul en HomeActivity es recomendable hacer un método, y envuelve en un try-catch el obtener el usuario. Cuando hay muchos traspasos de datos nos podemos confundir y la aplicación devolverá un ClassCastException.

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding= ActivityHomeBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

**MEJOR EN UN MÉTODO**
        **user= (User) getIntent().getParcelableExtra(USER);
        Log.e("Adrian","El usuario es "+user.getUsername()+" y la contraseña es "+user.getPassword());**
    }

**Comment by adrianfanjul** [comment]
Solucionado
