### ISSUE TITLE
RegisterActivity mejor un startActivityForResult

### ISSUE THREAD

**Issue by manelcc** [adrianfanjul/FlujoLogin#3]
@adrianfanjul  Cuando se lanza desde el login la Activity, es mejor con un startActvityForResult y no hace falta pasarle el objeto usuario, pues Registrer es quien crea el usuario y Login lo recibirá mediante el intento que se recibe en el onActivityResult o bien mediante el callback del registrerTask.

**Comment by adrianfanjul** [comment]
Solucionado
